import Domain
import Foundation

public extension RecipeEntity {
    
    static let mock = [
        RecipeEntity(id: 1,
                     title: "Traditional spare ribs baked",
                     image: "https://img.spoonacular.com/recipes/660048-556x370.jpg",
                     imageType: "jpg",
                     servings: 4,
                     readyInMinutes: 120,
                     sourceUrl: "https://example.com/recipe1"),
        
        RecipeEntity(id: 2,
                     title: "Lamb chops with fruity couscous and mint",
                     image: "https://img.spoonacular.com/recipes/716412-556x370.jpg",
                     imageType: "jpg",
                     servings: 2,
                     readyInMinutes: 45,
                     sourceUrl: "https://example.com/recipe2"),
        
        RecipeEntity(id: 3,
                     title: "Spice roasted chicken with flavored rice",
                     image: "https://img.spoonacular.com/recipes/634753-556x370.jpg",
                     imageType: "jpg",
                     servings: 3,
                     readyInMinutes: 60,
                     sourceUrl: "https://example.com/recipe3"),
        
        RecipeEntity(id: 4,
                     title: "Chinese style Egg fried rice with sliced pork",
                     image: "https://img.spoonacular.com/recipes/639137-556x370.jpg",
                     imageType: "jpg",
                     servings: 2,
                     readyInMinutes: 30,
                     sourceUrl: "https://example.com/recipe4"),
        
        RecipeEntity(id: 5,
                     title: "Vegetarian pasta primavera",
                     image: "https://img.spoonacular.com/recipes/664655-556x370.jpg",
                     imageType: "jpg",
                     servings: 4,
                     readyInMinutes: 35,
                     sourceUrl: "https://example.com/recipe5"),
        
        RecipeEntity(id: 6,
                     title: "Grilled salmon with lemon dill sauce",
                     image: "https://img.spoonacular.com/recipes/632570-556x370.jpg",
                     imageType: "jpg",
                     servings: 2,
                     readyInMinutes: 25,
                     sourceUrl: "https://example.com/recipe6"),
        
        RecipeEntity(id: 7,
                     title: "Roasted beef with garlic and rosemary",
                     image: "https://img.spoonacular.com/recipes/639769-556x370.jpg",
                     imageType: "jpg",
                     servings: 6,
                     readyInMinutes: 90,
                     sourceUrl: "https://example.com/recipe7"),
        
        RecipeEntity(id: 8,
                     title: "Chinese style Egg fried rice with sliced pork",
                     image: "https://img.spoonacular.com/recipes/641687-556x370.jpg",
                     imageType: "jpg",
                     servings: 2,
                     readyInMinutes: 30,
                     sourceUrl: "https://example.com/recipe8"),
        
        RecipeEntity(id: 9,
                     title: "Mexican style shrimp tacos",
                     image: "https://img.spoonacular.com/recipes/638741-556x370.jpg",
                     imageType: "jpg",
                     servings: 4,
                     readyInMinutes: 20,
                     sourceUrl: "https://example.com/recipe9"),
        
        RecipeEntity(id: 10,
                     title: "Creamy mushroom risotto",
                     image: "https://img.spoonacular.com/recipes/634431-556x370.jpg",
                     imageType: "jpg",
                     servings: 3,
                     readyInMinutes: 45,
                     sourceUrl: "https://example.com/recipe10"),
        
        RecipeEntity(id: 11,
                     title: "Vegetable stir-fry with tofu",
                     image: "https://img.spoonacular.com/recipes/657000-556x370.jpg",
                     imageType: "jpg",
                     servings: 2,
                     readyInMinutes: 25,
                     sourceUrl: "https://example.com/recipe11"),
        
        RecipeEntity(id: 12,
                     title: "Beef and broccoli stir-fry",
                     image: "https://img.spoonacular.com/recipes/651767-556x370.jpg",
                     imageType: "jpg",
                     servings: 4,
                     readyInMinutes: 30,
                     sourceUrl: "https://example.com/recipe12"),
        
        RecipeEntity(id: 13,
                     title: "Classic Italian pizza margherita",
                     image: "https://img.spoonacular.com/recipes/665172-556x370.jpg",
                     imageType: "jpg",
                     servings: 4,
                     readyInMinutes: 20,
                     sourceUrl: "https://example.com/recipe13"),
        
        RecipeEntity(id: 14,
                     title: "Spicy Thai green curry with chicken",
                     image: "https://img.spoonacular.com/recipes/658007-556x370.jpg",
                     imageType: "jpg",
                     servings: 3,
                     readyInMinutes: 40,
                     sourceUrl: "https://example.com/recipe14"),
        
        RecipeEntity(id: 15,
                     title: "Grilled vegetable kebabs",
                     image: "https://img.spoonacular.com/recipes/633068-556x370.jpg",
                     imageType: "jpg",
                     servings: 2,
                     readyInMinutes: 25,
                     sourceUrl: "https://example.com/recipe15"),
        
        RecipeEntity(id: 16,
                     title: "French onion soup",
                     image: "https://img.spoonacular.com/recipes/660266-556x370.jpg",
                     imageType: "jpg",
                     servings: 4,
                     readyInMinutes: 60,
                     sourceUrl: "https://example.com/recipe16"),
        
        RecipeEntity(id: 17,
                     title: "Mediterranean quinoa salad",
                     image: "https://img.spoonacular.com/recipes/633091-556x370.jpg",
                     imageType: "jpg",
                     servings: 2,
                     readyInMinutes: 15,
                     sourceUrl: "https://example.com/recipe17"),
        
        RecipeEntity(id: 18,
                     title: "BBQ pulled pork sliders",
                     image: "https://img.spoonacular.com/recipes/665182-556x370.jpg",
                     imageType: "jpg",
                     servings: 4,
                     readyInMinutes: 180,
                     sourceUrl: "https://example.com/recipe18"),
        
        RecipeEntity(id: 19,
                     title: "Chicken Caesar salad",
                     image: "https://img.spoonacular.com/recipes/664963-556x370.jpg",
                     imageType: "jpg",
                     servings: 2,
                     readyInMinutes: 20,
                     sourceUrl: "https://example.com/recipe19"),
        
        RecipeEntity(id: 20,
                     title: "Baked ziti with mozzarella and basil",
                     image: "https://img.spoonacular.com/recipes/636632-556x370.jpg",
                     imageType: "jpg",
                     servings: 4,
                     readyInMinutes: 50,
                     sourceUrl: "https://example.com/recipe20")
    ]
}
