public extension Recipe {
    static func makeMackRecipes() -> [Recipe] {
        return [
            Recipe(id: 1,
                   title: "Traditional spare ribs baked",
                   image: "https://example.com/ribs.jpg",
                   imageType: "jpg",
                   servings: 4,
                   readyInMinutes: 120,
                   sourceUrl: "https://example.com/recipe1",
                   nutrition: [Nutrition(title: "Calories", amount: 500, unit: "kcal")],
                   analyzedInstructions: [AnalyzedInstruction(name: "Cooking", steps: [Step(number: 1, step: "Preheat oven", ingredients: [], equipment: [])])]),
            
            Recipe(id: 2,
                   title: "Lamb chops with fruity couscous and mint",
                   image: "https://example.com/lamb.jpg",
                   imageType: "jpg",
                   servings: 2,
                   readyInMinutes: 45,
                   sourceUrl: "https://example.com/recipe2",
                   nutrition: [Nutrition(title: "Protein", amount: 30, unit: "g")],
                   analyzedInstructions: [AnalyzedInstruction(name: "Preparation", steps: [Step(number: 1, step: "Chop mint", ingredients: [], equipment: [])])]),
            
            Recipe(id: 3,
                   title: "Spice roasted chicken with flavored rice",
                   image: "https://example.com/chicken.jpg",
                   imageType: "jpg",
                   servings: 3,
                   readyInMinutes: 60,
                   sourceUrl: "https://example.com/recipe3",
                   nutrition: [Nutrition(title: "Fat", amount: 20, unit: "g")],
                   analyzedInstructions: [AnalyzedInstruction(name: "Cooking", steps: [Step(number: 1, step: "Marinate chicken", ingredients: [], equipment: [])])]),
            
            Recipe(id: 4,
                   title: "Chinese style Egg fried rice with sliced pork",
                   image: "https://example.com/fried_rice.jpg",
                   imageType: "jpg",
                   servings: 2,
                   readyInMinutes: 30,
                   sourceUrl: "https://example.com/recipe4",
                   nutrition: [Nutrition(title: "Carbs", amount: 70, unit: "g")],
                   analyzedInstructions: [AnalyzedInstruction(name: "Cooking", steps: [Step(number: 1, step: "Fry rice", ingredients: [], equipment: [])])]),
            Recipe(id: 5,
                   title: "Traditional spare ribs baked",
                   image: "https://example.com/ribs.jpg",
                   imageType: "jpg",
                   servings: 4,
                   readyInMinutes: 120,
                   sourceUrl: "https://example.com/recipe1",
                   nutrition: [Nutrition(title: "Calories", amount: 500, unit: "kcal")],
                   analyzedInstructions: [AnalyzedInstruction(name: "Cooking", steps: [Step(number: 1, step: "Preheat oven", ingredients: [], equipment: [])])]),
            
            Recipe(id: 6,
                   title: "Lamb chops with fruity couscous and mint",
                   image: "https://example.com/lamb.jpg",
                   imageType: "jpg",
                   servings: 2,
                   readyInMinutes: 45,
                   sourceUrl: "https://example.com/recipe2",
                   nutrition: [Nutrition(title: "Protein", amount: 30, unit: "g")],
                   analyzedInstructions: [AnalyzedInstruction(name: "Preparation", steps: [Step(number: 1, step: "Chop mint", ingredients: [], equipment: [])])]),
            
            Recipe(id: 7,
                   title: "Spice roasted chicken with flavored rice",
                   image: "https://example.com/chicken.jpg",
                   imageType: "jpg",
                   servings: 3,
                   readyInMinutes: 60,
                   sourceUrl: "https://example.com/recipe3",
                   nutrition: [Nutrition(title: "Fat", amount: 20, unit: "g")],
                   analyzedInstructions: [AnalyzedInstruction(name: "Cooking", steps: [Step(number: 1, step: "Marinate chicken", ingredients: [], equipment: [])])]),
            
            Recipe(id: 8,
                   title: "Chinese style Egg fried rice with sliced pork",
                   image: "https://example.com/fried_rice.jpg",
                   imageType: "jpg",
                   servings: 2,
                   readyInMinutes: 30,
                   sourceUrl: "https://example.com/recipe4",
                   nutrition: [Nutrition(title: "Carbs", amount: 70, unit: "g")],
                   analyzedInstructions: [AnalyzedInstruction(name: "Cooking", steps: [Step(number: 1, step: "Fry rice", ingredients: [], equipment: [])])])
        ]
    }
}
